# Generated by Django 3.2.4 on 2021-07-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile'), ('Desktop', 'Desktop'), ('Upcoming', 'Upcoming')], default='Web apps', max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('image_one', models.ImageField(upload_to='images/projects')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('image_six', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('image_seven', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('image_eight', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('image_nine', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('image_ten', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('image_eleven', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('image_twelve', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
