# Generated by Django 3.2.4 on 2021-07-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='name',
            new_name='title',
        ),
    ]
