# Generated by Django 3.2.4 on 2021-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210703_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('-start_date',)},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='date',
        ),
        migrations.AddField(
            model_name='resume',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
