# Generated by Django 3.2.4 on 2021-07-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210703_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
