# Generated by Django 3.2.4 on 2021-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_resume_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('upcoming', 'Upcoming')], default='Web apps', max_length=20),
        ),
    ]
