# Generated by Django 3.2.4 on 2021-07-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_twelve',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
    ]
