# Generated by Django 3.2.4 on 2021-07-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_project_image_four'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_facebook', models.URLField(blank=True, null=True)),
                ('my_twitter', models.URLField(blank=True, null=True)),
                ('my_linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
    ]
